version: '3.7'

services:
  crud-database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: crudDB
    container_name: crud-database
    ports:
      - "5432:5432"